### ISSUE TITLE
Release Code?

### ISSUE THREAD

**Issue by TruthSearcher** [damo-vilab/i2vgen-xl#2]

**Comment by Steven-SWZhang** [comment]
Thank you for your interest in our work. We are in the process of organizing the code and models, and we have plans to open-source multiple Image-to-video models. We appreciate your attention.

**Comment by ax-anoop** [comment]
Any timeline for release?

**Comment by Steven-SWZhang** [comment]
Hi, we plan to release the models and code probably early next month.

**Comment by howardgriffin** [comment]
waiting for the code

**Comment by ninjasaid2k** [comment]
Is there plans for release?

**Comment by TruthSearcher** [comment]
code is released.
