### ISSUE TITLE
T2V weights

### ISSUE THREAD

**Issue by zhw-zhang** [damo-vilab/i2vgen-xl#22]
Hello, thank you for your work. Where can I find the model that can generate the following video results? The original Modelscope-T2V weights should not be able to produce such good results. 
<img width="452" alt="image" src="https://github.com/damo-vilab/i2vgen-xl/assets/135094935/95001105-34f5-493f-bcb0-7d70bb9e1c67">

**Comment by Steven-SWZhang** [comment]
We have not yet made these high-definition T2V models public. Here, we have only released the training code and are supporting our already open-source T2V model, with the hope of making a limited contribution to the academic development of the community.
