### ISSUE TITLE
生成动图丢失了很多原图的细节，这一点的优化是否考虑进Road map里？

### ISSUE THREAD

**Issue by yunkchen** [damo-vilab/i2vgen-xl#3]
输入的图片应该是Dall-E-3 和 MJ 生成的，也许输入图片 和 生成过程用同一个基底模型效果会好一些；

猜想 弱化细节 是为了让i2v的过程变得更简单吧～

**Comment by Steven-SWZhang** [comment]
We have the model that completely preserves the details of input images, but the resolution will be a little lower, the duration will be shorter, and the Text+Image to Video model. If possible, we will also release them this repo. We welcome your attention.
