### ISSUE TITLE
Exception in inference_i2vgen_entrance: CUDA Invalid Configuration Argument

### ISSUE THREAD

**Issue by Limbicnation** [damo-vilab/i2vgen-xl#36]
Exception: Failed to invoke function <function inference_i2vgen_entrance at 0x7fedc8e90160>, with CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Steven-SWZhang** [comment]
Hello, this issue may be due to the version of xformer. For now, you can pull the latest code again, and the problem should not occur.

**Comment by Limbicnation** [comment]
Thank you!

Experiencing CUDA out of memory error while running on RTX4090, which seems to have insufficient VRAM:

Encountered a failure in the `train_t2v_entrance` function due to CUDA memory limitations. The process attempted to allocate an additional 80.00 MiB, but GPU 0, with a total capacity of 23.65 GiB, only had 32.38 MiB available. The current memory usage by this process is 22.52 GiB, with PyTorch allocating 21.22 GiB and reserving an unallocated 662.34 MiB. To manage this, consider adjusting `max_split_size_mb` to reduce fragmentation. Refer to the PyTorch documentation on Memory Management and `PYTORCH_CUDA_ALLOC_CONF` for more details.
